trajectory_execution:
  allowed_execution_duration_scaling: 5.0
  allowed_goal_duration_margin: 1.0
  allowed_start_tolerance: 1.0

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_names:
  - arm_controller

arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
